//
// RomFileSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RomFileSchema: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var romId: Int
    public var fileName: String
    public var filePath: String
    public var fileSizeBytes: Int
    public var fullPath: String
    public var createdAt: Date
    public var updatedAt: Date
    public var lastModified: Date?
    public var crcHash: String?
    public var md5Hash: String?
    public var sha1Hash: String?
    public var category: RomFileCategory?

    public init(id: Int, romId: Int, fileName: String, filePath: String, fileSizeBytes: Int, fullPath: String, createdAt: Date, updatedAt: Date, lastModified: Date?, crcHash: String?, md5Hash: String?, sha1Hash: String?, category: RomFileCategory?) {
        self.id = id
        self.romId = romId
        self.fileName = fileName
        self.filePath = filePath
        self.fileSizeBytes = fileSizeBytes
        self.fullPath = fullPath
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.lastModified = lastModified
        self.crcHash = crcHash
        self.md5Hash = md5Hash
        self.sha1Hash = sha1Hash
        self.category = category
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case romId = "rom_id"
        case fileName = "file_name"
        case filePath = "file_path"
        case fileSizeBytes = "file_size_bytes"
        case fullPath = "full_path"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case lastModified = "last_modified"
        case crcHash = "crc_hash"
        case md5Hash = "md5_hash"
        case sha1Hash = "sha1_hash"
        case category
    }

    // Decodable protocol methods
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(Int.self, forKey: .id)
        romId = try container.decode(Int.self, forKey: .romId)
        fileName = container.decodeFlexibleString(forKey: .fileName, default: "")
        filePath = container.decodeFlexibleString(forKey: .filePath, default: "")
        fileSizeBytes = try container.decode(Int.self, forKey: .fileSizeBytes)
        fullPath = container.decodeFlexibleString(forKey: .fullPath, default: "")
        createdAt = try container.decodeFlexibleDate(forKey: .createdAt)
        updatedAt = try container.decodeFlexibleDate(forKey: .updatedAt)
        lastModified = try container.decodeFlexibleDate(forKey: .lastModified)
        crcHash = try container.decodeIfPresent(String.self, forKey: .crcHash)
        md5Hash = try container.decodeIfPresent(String.self, forKey: .md5Hash)
        sha1Hash = try container.decodeIfPresent(String.self, forKey: .sha1Hash)
        category = try container.decodeIfPresent(RomFileCategory.self, forKey: .category)
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(romId, forKey: .romId)
        try container.encode(fileName, forKey: .fileName)
        try container.encode(filePath, forKey: .filePath)
        try container.encode(fileSizeBytes, forKey: .fileSizeBytes)
        try container.encode(fullPath, forKey: .fullPath)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(lastModified, forKey: .lastModified)
        try container.encode(crcHash, forKey: .crcHash)
        try container.encode(md5Hash, forKey: .md5Hash)
        try container.encode(sha1Hash, forKey: .sha1Hash)
        try container.encode(category, forKey: .category)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RomFileSchema: Identifiable {}
