//
// RomMetadataSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RomMetadataSchema: Codable, JSONEncodable, Hashable {

    public var romId: Int
    public var genres: [String]
    public var franchises: [String]
    public var collections: [String]
    public var companies: [String]
    public var gameModes: [String]
    public var ageRatings: [String]
    public var firstReleaseDate: Int?
    public var averageRating: Double?

    public init(romId: Int, genres: [String], franchises: [String], collections: [String], companies: [String], gameModes: [String], ageRatings: [String], firstReleaseDate: Int?, averageRating: Double?) {
        self.romId = romId
        self.genres = genres
        self.franchises = franchises
        self.collections = collections
        self.companies = companies
        self.gameModes = gameModes
        self.ageRatings = ageRatings
        self.firstReleaseDate = firstReleaseDate
        self.averageRating = averageRating
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case romId = "rom_id"
        case genres
        case franchises
        case collections
        case companies
        case gameModes = "game_modes"
        case ageRatings = "age_ratings"
        case firstReleaseDate = "first_release_date"
        case averageRating = "average_rating"
    }

    // Decodable protocol methods
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        romId = try container.decode(Int.self, forKey: .romId)
        genres = container.decodeIfPresentOrDefault([String].self, forKey: .genres, default: [])
        franchises = container.decodeIfPresentOrDefault([String].self, forKey: .franchises, default: [])
        collections = container.decodeIfPresentOrDefault([String].self, forKey: .collections, default: [])
        companies = container.decodeIfPresentOrDefault([String].self, forKey: .companies, default: [])
        gameModes = container.decodeIfPresentOrDefault([String].self, forKey: .gameModes, default: [])
        ageRatings = container.decodeIfPresentOrDefault([String].self, forKey: .ageRatings, default: [])
        firstReleaseDate = try container.decodeIfPresent(Int.self, forKey: .firstReleaseDate)
        averageRating = try container.decodeIfPresent(Double.self, forKey: .averageRating)
    }

    /// Fallback used when the server omits or nulls the `metadatum` object entirely
    /// (observed on some RomM 5.x detail responses for sparsely-identified ROMs).
    static func empty(romId: Int) -> RomMetadataSchema {
        RomMetadataSchema(
            romId: romId,
            genres: [],
            franchises: [],
            collections: [],
            companies: [],
            gameModes: [],
            ageRatings: [],
            firstReleaseDate: nil,
            averageRating: nil
        )
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(romId, forKey: .romId)
        try container.encode(genres, forKey: .genres)
        try container.encode(franchises, forKey: .franchises)
        try container.encode(collections, forKey: .collections)
        try container.encode(companies, forKey: .companies)
        try container.encode(gameModes, forKey: .gameModes)
        try container.encode(ageRatings, forKey: .ageRatings)
        try container.encode(firstReleaseDate, forKey: .firstReleaseDate)
        try container.encode(averageRating, forKey: .averageRating)
    }
}

