//
// RomUserSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RomUserSchema: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var userId: Int
    public var romId: Int
    public var createdAt: Date
    public var updatedAt: Date
    public var lastPlayed: Date?
    public var noteRawMarkdown: String?
    public var noteIsPublic: Bool?
    public var isMainSibling: Bool?
    public var backlogged: Bool
    public var nowPlaying: Bool
    public var hidden: Bool
    public var rating: Int
    public var difficulty: Int
    public var completion: Int
    public var status: RomUserStatus?
    public var userUsername: String

    public init(id: Int, userId: Int, romId: Int, createdAt: Date, updatedAt: Date, lastPlayed: Date?, noteRawMarkdown: String?, noteIsPublic: Bool?, isMainSibling: Bool?, backlogged: Bool, nowPlaying: Bool, hidden: Bool, rating: Int, difficulty: Int, completion: Int, status: RomUserStatus?, userUsername: String) {
        self.id = id
        self.userId = userId
        self.romId = romId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.lastPlayed = lastPlayed
        self.noteRawMarkdown = noteRawMarkdown
        self.noteIsPublic = noteIsPublic
        self.isMainSibling = isMainSibling
        self.backlogged = backlogged
        self.nowPlaying = nowPlaying
        self.hidden = hidden
        self.rating = rating
        self.difficulty = difficulty
        self.completion = completion
        self.status = status
        self.userUsername = userUsername
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userId = "user_id"
        case romId = "rom_id"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case lastPlayed = "last_played"
        case noteRawMarkdown = "note_raw_markdown"
        case noteIsPublic = "note_is_public"
        case isMainSibling = "is_main_sibling"
        case backlogged
        case nowPlaying = "now_playing"
        case hidden
        case rating
        case difficulty
        case completion
        case status
        case userUsername = "user__username"
    }

    // Decodable protocol methods
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(Int.self, forKey: .id)
        userId = try container.decode(Int.self, forKey: .userId)
        romId = try container.decode(Int.self, forKey: .romId)
        createdAt = try container.decodeFlexibleDate(forKey: .createdAt)
        updatedAt = try container.decodeFlexibleDate(forKey: .updatedAt)
        // Handle optional Date field
        if container.contains(.lastPlayed) {
            lastPlayed = try? container.decodeFlexibleDate(forKey: .lastPlayed)
        } else {
            lastPlayed = nil
        }
        noteRawMarkdown = try container.decodeIfPresent(String.self, forKey: .noteRawMarkdown)
        noteIsPublic = try container.decodeIfPresent(Bool.self, forKey: .noteIsPublic)
        isMainSibling = try container.decodeIfPresent(Bool.self, forKey: .isMainSibling)
        backlogged = container.decodeFlexibleBool(forKey: .backlogged, default: false)
        nowPlaying = container.decodeFlexibleBool(forKey: .nowPlaying, default: false)
        hidden = container.decodeFlexibleBool(forKey: .hidden, default: false)
        rating = container.decodeFlexibleInt(forKey: .rating, default: 0)
        difficulty = container.decodeFlexibleInt(forKey: .difficulty, default: 0)
        completion = container.decodeFlexibleInt(forKey: .completion, default: 0)
        status = try container.decodeIfPresent(RomUserStatus.self, forKey: .status)
        userUsername = container.decodeFlexibleString(forKey: .userUsername, default: "")
    }

    /// Fallback used when the server omits or nulls the `rom_user` object entirely
    /// (observed on some RomM 5.x detail responses). Keeps detail decoding from
    /// failing outright, which would otherwise surface as a generic network error.
    static func empty(romId: Int) -> RomUserSchema {
        RomUserSchema(
            id: 0,
            userId: 0,
            romId: romId,
            createdAt: .distantPast,
            updatedAt: .distantPast,
            lastPlayed: nil,
            noteRawMarkdown: nil,
            noteIsPublic: nil,
            isMainSibling: nil,
            backlogged: false,
            nowPlaying: false,
            hidden: false,
            rating: 0,
            difficulty: 0,
            completion: 0,
            status: nil,
            userUsername: ""
        )
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(romId, forKey: .romId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(lastPlayed, forKey: .lastPlayed)
        try container.encodeIfPresent(noteRawMarkdown, forKey: .noteRawMarkdown)
        try container.encodeIfPresent(noteIsPublic, forKey: .noteIsPublic)
        try container.encodeIfPresent(isMainSibling, forKey: .isMainSibling)
        try container.encode(backlogged, forKey: .backlogged)
        try container.encode(nowPlaying, forKey: .nowPlaying)
        try container.encode(hidden, forKey: .hidden)
        try container.encode(rating, forKey: .rating)
        try container.encode(difficulty, forKey: .difficulty)
        try container.encode(completion, forKey: .completion)
        try container.encode(status, forKey: .status)
        try container.encode(userUsername, forKey: .userUsername)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RomUserSchema: Identifiable {}
