//
// SaveSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SaveSchema: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var romId: Int
    public var userId: Int
    public var fileName: String
    public var fileNameNoTags: String
    public var fileNameNoExt: String
    public var fileExtension: String
    public var filePath: String
    public var fileSizeBytes: Int
    public var fullPath: String
    public var downloadPath: String
    public var missingFromFs: Bool
    public var createdAt: Date
    public var updatedAt: Date
    public var emulator: String?
    public var screenshot: ScreenshotSchema?
    /// Filed server-side since RomM 4.7.0 (backend/models/assets.py); a save
    /// without a slot is a legacy/archival entry that never pairs with a
    /// client slot (see `SaveSlot`).
    public var slot: String?
    /// MD5 hex the server stores for the save's content (`content_hash`).
    /// Lets a client tell a byte-identical duplicate apart from a genuinely
    /// different save without downloading it first.
    public var contentHash: String?
    /// The device that first uploaded this save (`origin_device_id`).
    public var originDeviceId: String?
    /// Per-device download bookkeeping for this save (`device_syncs`).
    public var deviceSyncs: [DeviceSyncSchema]?

    public init(id: Int, romId: Int, userId: Int, fileName: String, fileNameNoTags: String, fileNameNoExt: String, fileExtension: String, filePath: String, fileSizeBytes: Int, fullPath: String, downloadPath: String, missingFromFs: Bool, createdAt: Date, updatedAt: Date, emulator: String?, screenshot: ScreenshotSchema?, slot: String? = nil, contentHash: String? = nil, originDeviceId: String? = nil, deviceSyncs: [DeviceSyncSchema]? = nil) {
        self.id = id
        self.romId = romId
        self.userId = userId
        self.fileName = fileName
        self.fileNameNoTags = fileNameNoTags
        self.fileNameNoExt = fileNameNoExt
        self.fileExtension = fileExtension
        self.filePath = filePath
        self.fileSizeBytes = fileSizeBytes
        self.fullPath = fullPath
        self.downloadPath = downloadPath
        self.missingFromFs = missingFromFs
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.emulator = emulator
        self.screenshot = screenshot
        self.slot = slot
        self.contentHash = contentHash
        self.originDeviceId = originDeviceId
        self.deviceSyncs = deviceSyncs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case romId = "rom_id"
        case userId = "user_id"
        case fileName = "file_name"
        case fileNameNoTags = "file_name_no_tags"
        case fileNameNoExt = "file_name_no_ext"
        case fileExtension = "file_extension"
        case filePath = "file_path"
        case fileSizeBytes = "file_size_bytes"
        case fullPath = "full_path"
        case downloadPath = "download_path"
        case missingFromFs = "missing_from_fs"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case emulator
        case screenshot
        case slot
        case contentHash = "content_hash"
        case originDeviceId = "origin_device_id"
        case deviceSyncs = "device_syncs"
    }

    // Decodable protocol methods
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(Int.self, forKey: .id)
        romId = try container.decode(Int.self, forKey: .romId)
        userId = try container.decode(Int.self, forKey: .userId)
        fileName = try container.decode(String.self, forKey: .fileName)
        fileNameNoTags = try container.decode(String.self, forKey: .fileNameNoTags)
        fileNameNoExt = try container.decode(String.self, forKey: .fileNameNoExt)
        fileExtension = try container.decode(String.self, forKey: .fileExtension)
        filePath = try container.decode(String.self, forKey: .filePath)
        fileSizeBytes = try container.decode(Int.self, forKey: .fileSizeBytes)
        fullPath = try container.decode(String.self, forKey: .fullPath)
        downloadPath = try container.decode(String.self, forKey: .downloadPath)
        missingFromFs = try container.decode(Bool.self, forKey: .missingFromFs)
        createdAt = try container.decodeFlexibleDate(forKey: .createdAt)
        updatedAt = try container.decodeFlexibleDate(forKey: .updatedAt)
        emulator = try container.decodeIfPresent(String.self, forKey: .emulator)
        screenshot = try container.decodeIfPresent(ScreenshotSchema.self, forKey: .screenshot)
        slot = try container.decodeIfPresent(String.self, forKey: .slot)
        contentHash = try container.decodeIfPresent(String.self, forKey: .contentHash)
        originDeviceId = try container.decodeIfPresent(String.self, forKey: .originDeviceId)
        deviceSyncs = try container.decodeIfPresent([DeviceSyncSchema].self, forKey: .deviceSyncs)
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(romId, forKey: .romId)
        try container.encode(userId, forKey: .userId)
        try container.encode(fileName, forKey: .fileName)
        try container.encode(fileNameNoTags, forKey: .fileNameNoTags)
        try container.encode(fileNameNoExt, forKey: .fileNameNoExt)
        try container.encode(fileExtension, forKey: .fileExtension)
        try container.encode(filePath, forKey: .filePath)
        try container.encode(fileSizeBytes, forKey: .fileSizeBytes)
        try container.encode(fullPath, forKey: .fullPath)
        try container.encode(downloadPath, forKey: .downloadPath)
        try container.encode(missingFromFs, forKey: .missingFromFs)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(emulator, forKey: .emulator)
        try container.encode(screenshot, forKey: .screenshot)
        try container.encode(slot, forKey: .slot)
        try container.encode(contentHash, forKey: .contentHash)
        try container.encode(originDeviceId, forKey: .originDeviceId)
        try container.encode(deviceSyncs, forKey: .deviceSyncs)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SaveSchema: Identifiable {}

/// Per-device download bookkeeping for one save (`DeviceSyncSchema`), the row
/// `POST /api/saves/{id}/downloaded` writes.
public struct DeviceSyncSchema: Codable, Hashable {
    public var deviceId: String
    public var deviceName: String?
    public var lastSyncedAt: Date?
    public var isUntracked: Bool
    public var isCurrent: Bool

    public init(deviceId: String, deviceName: String? = nil, lastSyncedAt: Date? = nil, isUntracked: Bool = false, isCurrent: Bool = false) {
        self.deviceId = deviceId
        self.deviceName = deviceName
        self.lastSyncedAt = lastSyncedAt
        self.isUntracked = isUntracked
        self.isCurrent = isCurrent
    }

    public enum CodingKeys: String, CodingKey {
        case deviceId = "device_id"
        case deviceName = "device_name"
        case lastSyncedAt = "last_synced_at"
        case isUntracked = "is_untracked"
        case isCurrent = "is_current"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        deviceId = try container.decode(String.self, forKey: .deviceId)
        deviceName = try container.decodeIfPresent(String.self, forKey: .deviceName)
        lastSyncedAt = try container.decodeFlexibleDate(forKey: .lastSyncedAt)
        isUntracked = try container.decodeIfPresent(Bool.self, forKey: .isUntracked) ?? false
        isCurrent = try container.decodeIfPresent(Bool.self, forKey: .isCurrent) ?? false
    }
}
