//
// SimpleRomSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SimpleRomSchema: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var igdbId: Int?
    public var sgdbId: Int?
    public var mobyId: Int?
    public var ssId: Int?
    public var raId: Int?
    public var launchboxId: Int?
    public var hasheousId: Int?
    public var tgdbId: Int?
    public var platformId: Int
    public var platformSlug: String
    public var platformFsSlug: String
    public var platformName: String
    public var platformCustomName: String?
    public var platformDisplayName: String
    public var fsName: String
    public var fsNameNoTags: String
    public var fsNameNoExt: String
    public var fsExtension: String
    public var fsPath: String
    public var fsSizeBytes: Int
    public var name: String?
    public var slug: String?
    public var summary: String?
    public var alternativeNames: [String]
    public var youtubeVideoId: String?
    public var metadatum: RomMetadataSchema
    public var igdbMetadata: RomIGDBMetadata?
    public var mobyMetadata: RomMobyMetadata?
    public var ssMetadata: RomSSMetadata?
    public var launchboxMetadata: RomLaunchboxMetadata?
    public var hasheousMetadata: RomHasheousMetadata?
    public var pathCoverSmall: String?
    public var pathCoverLarge: String?
    public var urlCover: String?
    public var hasManual: Bool
    public var pathManual: String?
    public var urlManual: String?
    public var isUnidentified: Bool
    public var isIdentified: Bool
    public var revision: String?
    public var regions: [String]
    public var languages: [String]
    public var tags: [String]
    public var crcHash: String?
    public var md5Hash: String?
    public var sha1Hash: String?
    public var multi: Bool?
    public var files: [RomFileSchema]
    public var fullPath: String
    public var createdAt: Date
    public var updatedAt: Date
    public var missingFromFs: Bool
    public var siblings: [SiblingRomSchema]
    public var romUser: RomUserSchema

    public init(id: Int, igdbId: Int?, sgdbId: Int?, mobyId: Int?, ssId: Int?, raId: Int?, launchboxId: Int?, hasheousId: Int?, tgdbId: Int?, platformId: Int, platformSlug: String, platformFsSlug: String, platformName: String, platformCustomName: String?, platformDisplayName: String, fsName: String, fsNameNoTags: String, fsNameNoExt: String, fsExtension: String, fsPath: String, fsSizeBytes: Int, name: String?, slug: String?, summary: String?, alternativeNames: [String], youtubeVideoId: String?, metadatum: RomMetadataSchema, igdbMetadata: RomIGDBMetadata?, mobyMetadata: RomMobyMetadata?, ssMetadata: RomSSMetadata?, launchboxMetadata: RomLaunchboxMetadata?, hasheousMetadata: RomHasheousMetadata?, pathCoverSmall: String?, pathCoverLarge: String?, urlCover: String?, hasManual: Bool, pathManual: String?, urlManual: String?, isUnidentified: Bool, isIdentified: Bool, revision: String?, regions: [String], languages: [String], tags: [String], crcHash: String?, md5Hash: String?, sha1Hash: String?, multi: Bool?, files: [RomFileSchema], fullPath: String, createdAt: Date, updatedAt: Date, missingFromFs: Bool, siblings: [SiblingRomSchema], romUser: RomUserSchema) {
        self.id = id
        self.igdbId = igdbId
        self.sgdbId = sgdbId
        self.mobyId = mobyId
        self.ssId = ssId
        self.raId = raId
        self.launchboxId = launchboxId
        self.hasheousId = hasheousId
        self.tgdbId = tgdbId
        self.platformId = platformId
        self.platformSlug = platformSlug
        self.platformFsSlug = platformFsSlug
        self.platformName = platformName
        self.platformCustomName = platformCustomName
        self.platformDisplayName = platformDisplayName
        self.fsName = fsName
        self.fsNameNoTags = fsNameNoTags
        self.fsNameNoExt = fsNameNoExt
        self.fsExtension = fsExtension
        self.fsPath = fsPath
        self.fsSizeBytes = fsSizeBytes
        self.name = name
        self.slug = slug
        self.summary = summary
        self.alternativeNames = alternativeNames
        self.youtubeVideoId = youtubeVideoId
        self.metadatum = metadatum
        self.igdbMetadata = igdbMetadata
        self.mobyMetadata = mobyMetadata
        self.ssMetadata = ssMetadata
        self.launchboxMetadata = launchboxMetadata
        self.hasheousMetadata = hasheousMetadata
        self.pathCoverSmall = pathCoverSmall
        self.pathCoverLarge = pathCoverLarge
        self.urlCover = urlCover
        self.hasManual = hasManual
        self.pathManual = pathManual
        self.urlManual = urlManual
        self.isUnidentified = isUnidentified
        self.isIdentified = isIdentified
        self.revision = revision
        self.regions = regions
        self.languages = languages
        self.tags = tags
        self.crcHash = crcHash
        self.md5Hash = md5Hash
        self.sha1Hash = sha1Hash
        self.multi = multi
        self.files = files
        self.fullPath = fullPath
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.missingFromFs = missingFromFs
        self.siblings = siblings
        self.romUser = romUser
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case igdbId = "igdb_id"
        case sgdbId = "sgdb_id"
        case mobyId = "moby_id"
        case ssId = "ss_id"
        case raId = "ra_id"
        case launchboxId = "launchbox_id"
        case hasheousId = "hasheous_id"
        case tgdbId = "tgdb_id"
        case platformId = "platform_id"
        case platformSlug = "platform_slug"
        case platformFsSlug = "platform_fs_slug"        
        case platformCustomName = "platform_custom_name"
        case platformDisplayName = "platform_display_name"
        case platformName = "platform_name"
        case fsName = "fs_name"
        case fsNameNoTags = "fs_name_no_tags"
        case fsNameNoExt = "fs_name_no_ext"
        case fsExtension = "fs_extension"
        case fsPath = "fs_path"
        case fsSizeBytes = "fs_size_bytes"
        case name
        case slug
        case summary
        case alternativeNames = "alternative_names"
        case youtubeVideoId = "youtube_video_id"
        case metadatum
        case igdbMetadata = "igdb_metadata"
        case mobyMetadata = "moby_metadata"
        case ssMetadata = "ss_metadata"
        case launchboxMetadata = "launchbox_metadata"
        case hasheousMetadata = "hasheous_metadata"
        case pathCoverSmall = "path_cover_small"
        case pathCoverLarge = "path_cover_large"
        case urlCover = "url_cover"
        case hasManual = "has_manual"
        case pathManual = "path_manual"
        case urlManual = "url_manual"
        case isUnidentified = "is_unidentified"
        case isIdentified = "is_identified"
        case revision
        case regions
        case languages
        case tags
        case crcHash = "crc_hash"
        case md5Hash = "md5_hash"
        case sha1Hash = "sha1_hash"
        case multi
        case files
        case fullPath = "full_path"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case missingFromFs = "missing_from_fs"
        case siblings = "sibling_roms"
        case romUser = "rom_user"
    }

    // Decodable protocol methods
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(Int.self, forKey: .id)
        igdbId = try container.decodeIfPresent(Int.self, forKey: .igdbId)
        sgdbId = try container.decodeIfPresent(Int.self, forKey: .sgdbId)
        mobyId = try container.decodeIfPresent(Int.self, forKey: .mobyId)
        ssId = try container.decodeIfPresent(Int.self, forKey: .ssId)
        raId = try container.decodeIfPresent(Int.self, forKey: .raId)
        launchboxId = try container.decodeIfPresent(Int.self, forKey: .launchboxId)
        hasheousId = try container.decodeIfPresent(Int.self, forKey: .hasheousId)
        tgdbId = try container.decodeIfPresent(Int.self, forKey: .tgdbId)
        platformId = try container.decode(Int.self, forKey: .platformId)
        platformSlug = try container.decode(String.self, forKey: .platformSlug)
        platformFsSlug = try container.decode(String.self, forKey: .platformFsSlug)
        platformName = container.decodeFlexibleString(forKey: .platformName, default: "")
        platformCustomName = try container.decodeIfPresent(String.self, forKey: .platformCustomName)
        platformDisplayName = container.decodeFlexibleString(forKey: .platformDisplayName, default: "")
        fsName = container.decodeFlexibleString(forKey: .fsName, default: "")
        fsNameNoTags = container.decodeFlexibleString(forKey: .fsNameNoTags, default: "")
        fsNameNoExt = container.decodeFlexibleString(forKey: .fsNameNoExt, default: "")
        fsExtension = container.decodeFlexibleString(forKey: .fsExtension, default: "")
        fsPath = container.decodeFlexibleString(forKey: .fsPath, default: "")
        fsSizeBytes = try container.decode(Int.self, forKey: .fsSizeBytes)
        name = try container.decodeIfPresent(String.self, forKey: .name)
        slug = try container.decodeIfPresent(String.self, forKey: .slug)
        summary = try container.decodeIfPresent(String.self, forKey: .summary)
        alternativeNames = container.decodeIfPresentOrDefault([String].self, forKey: .alternativeNames, default: [])
        youtubeVideoId = try container.decodeIfPresent(String.self, forKey: .youtubeVideoId)
        metadatum = try container.decode(RomMetadataSchema.self, forKey: .metadatum)
        igdbMetadata = try container.decodeIfPresent(RomIGDBMetadata.self, forKey: .igdbMetadata)
        mobyMetadata = try container.decodeIfPresent(RomMobyMetadata.self, forKey: .mobyMetadata)
        ssMetadata = try container.decodeIfPresent(RomSSMetadata.self, forKey: .ssMetadata)
        launchboxMetadata = try container.decodeIfPresent(RomLaunchboxMetadata.self, forKey: .launchboxMetadata)
        hasheousMetadata = try container.decodeIfPresent(RomHasheousMetadata.self, forKey: .hasheousMetadata)
        pathCoverSmall = try container.decodeIfPresent(String.self, forKey: .pathCoverSmall)
        pathCoverLarge = try container.decodeIfPresent(String.self, forKey: .pathCoverLarge)
        urlCover = try container.decodeIfPresent(String.self, forKey: .urlCover)
        hasManual = container.decodeFlexibleBool(forKey: .hasManual, default: false)
        pathManual = try container.decodeIfPresent(String.self, forKey: .pathManual)
        urlManual = try container.decodeIfPresent(String.self, forKey: .urlManual)
        isUnidentified = container.decodeFlexibleBool(forKey: .isUnidentified, default: false)
        isIdentified = container.decodeFlexibleBool(forKey: .isIdentified, default: false)
        revision = try container.decodeIfPresent(String.self, forKey: .revision)
        regions = container.decodeIfPresentOrDefault([String].self, forKey: .regions, default: [])
        languages = container.decodeIfPresentOrDefault([String].self, forKey: .languages, default: [])
        tags = container.decodeIfPresentOrDefault([String].self, forKey: .tags, default: [])
        crcHash = try container.decodeIfPresent(String.self, forKey: .crcHash)
        md5Hash = try container.decodeIfPresent(String.self, forKey: .md5Hash)
        sha1Hash = try container.decodeIfPresent(String.self, forKey: .sha1Hash)
        multi = try container.decodeIfPresent(Bool.self, forKey: .multi)
        files = container.decodeLossyArray(RomFileSchema.self, forKey: .files)
        fullPath = try container.decode(String.self, forKey: .fullPath)
        createdAt = try container.decodeFlexibleDate(forKey: .createdAt)
        updatedAt = try container.decodeFlexibleDate(forKey: .updatedAt)
        missingFromFs = try container.decode(Bool.self, forKey: .missingFromFs)
        siblings = try container.decode([SiblingRomSchema].self, forKey: .siblings)
        romUser = try container.decode(RomUserSchema.self, forKey: .romUser)
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(igdbId, forKey: .igdbId)
        try container.encode(sgdbId, forKey: .sgdbId)
        try container.encode(mobyId, forKey: .mobyId)
        try container.encode(ssId, forKey: .ssId)
        try container.encode(raId, forKey: .raId)
        try container.encode(launchboxId, forKey: .launchboxId)
        try container.encode(hasheousId, forKey: .hasheousId)
        try container.encode(tgdbId, forKey: .tgdbId)
        try container.encode(platformId, forKey: .platformId)
        try container.encode(platformSlug, forKey: .platformSlug)
        try container.encode(platformFsSlug, forKey: .platformFsSlug)
        try container.encode(platformCustomName, forKey: .platformCustomName)
        try container.encode(platformDisplayName, forKey: .platformDisplayName)
        try container.encode(fsName, forKey: .fsName)
        try container.encode(fsNameNoTags, forKey: .fsNameNoTags)
        try container.encode(fsNameNoExt, forKey: .fsNameNoExt)
        try container.encode(fsExtension, forKey: .fsExtension)
        try container.encode(fsPath, forKey: .fsPath)
        try container.encode(fsSizeBytes, forKey: .fsSizeBytes)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encode(summary, forKey: .summary)
        try container.encode(alternativeNames, forKey: .alternativeNames)
        try container.encode(youtubeVideoId, forKey: .youtubeVideoId)
        try container.encode(metadatum, forKey: .metadatum)
        try container.encode(igdbMetadata, forKey: .igdbMetadata)
        try container.encode(mobyMetadata, forKey: .mobyMetadata)
        try container.encode(ssMetadata, forKey: .ssMetadata)
        try container.encode(launchboxMetadata, forKey: .launchboxMetadata)
        try container.encode(hasheousMetadata, forKey: .hasheousMetadata)
        try container.encode(pathCoverSmall, forKey: .pathCoverSmall)
        try container.encode(pathCoverLarge, forKey: .pathCoverLarge)
        try container.encode(urlCover, forKey: .urlCover)
        try container.encode(hasManual, forKey: .hasManual)
        try container.encode(pathManual, forKey: .pathManual)
        try container.encode(urlManual, forKey: .urlManual)
        try container.encode(isUnidentified, forKey: .isUnidentified)
        try container.encode(isIdentified, forKey: .isIdentified)
        try container.encode(revision, forKey: .revision)
        try container.encode(regions, forKey: .regions)
        try container.encode(languages, forKey: .languages)
        try container.encode(tags, forKey: .tags)
        try container.encode(crcHash, forKey: .crcHash)
        try container.encode(md5Hash, forKey: .md5Hash)
        try container.encode(sha1Hash, forKey: .sha1Hash)
        try container.encodeIfPresent(multi, forKey: .multi)
        try container.encode(files, forKey: .files)
        try container.encode(fullPath, forKey: .fullPath)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(missingFromFs, forKey: .missingFromFs)
        try container.encode(siblings, forKey: .siblings)
        try container.encode(romUser, forKey: .romUser)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SimpleRomSchema: Identifiable {}

